### ISSUE TITLE
Update the PR flow so that all tests pass before merging into main.

### ISSUE THREAD

**Issue by Zolkin1** [Zolkin1/torc#3]
Just want to automate running the tests before merging into main. I think we can do this via a CI tool.

**Comment by gavin-hyl** [comment]
Of course, I'll take a look into it.

**Comment by Zolkin1** [comment]
I can actually handle this one (and the other issue I've posted). I think if you wanted to get started on the Quadratic cost class that would be a good use of time though.

**Comment by gavin-hyl** [comment]
Of course. I did some work in the quadratic class in a new branch, and had some questions about error-checking. Do we assume the quadratic form matrix provided by the user is symmetric? Also, do we let Eigen handle errors for incorrect dimensions, or do we implement our own error-checking?

Best,
Gavin Hua

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Zolkin1** [comment]
I think we can assume its symmetric - so we can maybe let the user pass in just an upper triangular part or they can pass in the full matrix and we can just use the upper triangular part. I think we can let Eigen handle size errors (at least for now). Also feel free to open a PR or an issue and we can discuss more there just to keep this thread related to the starting issue.

**Comment by gavin-hyl** [comment]
Got it, thanks for the information.
________________________________
